### ISSUE TITLE
Username Gitlab?

### ISSUE THREAD

**Issue by JuliaRietveld** [hellofromtonya/hello-child-theme#1]
Hi Tonya,
I'm currently watching your serie on how to make a child theme for Genesis. I tried to install your hello-child-theme via iTerm and this command: git clone https://gitlab.com/hellofromtonya/hello-child-theme.git But I get an error: _Username for 'https://gitlab.com':_  I don't have an account at gitlab.
When I download the theme and install it manually, after activating the Genesis and then your theme I get a white screen. :(
I want to learn this stuff so much! Thank you for your replay.
Greetings,
Julia

**Comment by hellofromtonya** [comment]
Hello Julia,
1. I had a bad address in the README.md, which I fixed for you. https://github.com/hellofromtonya/hello-child-theme.git
2. There are a lot of [dependencies](https://github.com/hellofromtonya/hello-child-theme#dependencies) required for this particular theme.  The list of them are specified [here](https://github.com/hellofromtonya/hello-child-theme#dependencies).  For example, you have to have Fulcrum installed _before_ you run this theme.

Cheers,
Tonya

P.S. If you want to learn how to build a custom child theme like this one, I teach you in this lab series on [Know the Code](https://knowthecode.io/series/lets-build-custom-developers-genesis-starter-child-theme):

[Let's Build a Custom Developer's Genesis Starter Child Theme](https://knowthecode.io/series/lets-build-custom-developers-genesis-starter-child-theme)

It will not require Fulcrum.

**Comment by hellofromtonya** [comment]
Also here is the Genesis-powered child theme for [Know the Code](https://github.com/KnowTheCode/KTC-Child-Theme).  Fulcrum is optional with it. 

And here is the [Genesis Starter Theme](https://github.com/KnowTheCode/Genesis-Developers-Starter-Theme) that you will build in this [lab](https://knowthecode.io/series/lets-build-custom-developers-genesis-starter-child-theme).  I provide step-by-step instructions, explanations, and details within the lab to help you build your own.
